// Project data for the "Product Lab" section. Add new projects at the end of the array.
// kind decides which UI board is drawn on the 3D slab: dashboard | mobile | chat | editor | diagram | grid
// statusType: 'dev' | 'live' | 'soon'
export const projects = [
  {
    id: "hris",
    kind: "dashboard",
    name: "Bitlabs HRIS",
    subtitle: "Human Resource Information System",
    desc: "A full-stack HRIS platform built for Sri Lankan enterprises. Manages the complete employee lifecycle — from onboarding and department assignment to attendance tracking, leave management, shift scheduling and payroll processing. Designed with real-world compliance requirements and multi-role access control in mind.",
    status: "In Development",
    statusType: "dev",
    tags: [
      "Next.js",
      "TypeScript",
      "PostgreSQL",
      "Drizzle ORM",
      "NextAuth",
      "Sentry",
    ],
    modules: [
      "Employees",
      "Attendance",
      "Leave",
      "Payroll",
      "Shifts",
      "Departments",
      "Calendar",
      "Audit Trail",
    ],
    visual: {
      title: "bitlabs-hris · dashboard",
      footer: ["Role-based access control", "Multi-company ready"],
    },
    link: null,
  },
  {
    id: "sfa",
    kind: "dashboard",
    name: "Bitlabs SFA",
    subtitle: "Sales Force Automation",
    desc: "An enterprise-grade Sales Force Automation platform built for field sales operations across Sri Lanka. Covers distributor network management, territory hierarchies, route planning, outlet visits, and real-time inventory — with a Flutter mobile app for field reps and a Next.js web dashboard for managers and executives.",
    status: "In Development",
    statusType: "dev",
    tags: [".NET 8", "Next.js", "Flutter", "PostgreSQL", "Redis", "TypeScript"],
    modules: [
      "Distributors",
      "Territories",
      "Routes",
      "Outlets",
      "Products",
      "Orders",
      "Mobile Sync",
      "Reports",
    ],
    visual: {
      title: "bitlabs-sfa · dashboard",
      footer: ["Offline-first mobile app", "Multi-territory ready"],
    },
    link: null,
  },
  {
    id: "goalie-gym",
    kind: "mobile",
    name: "Goalie Concentration Gym",
    subtitle: "Sports Cognitive Training App",
    desc: "A Flutter mobile app that sharpens goalies' reaction time and situational awareness through interactive grid-based training drills. Players race through number-sequence grids with animated distractions, while the app tracks reaction time, accuracy, and inter-tap intervals across every session.",
    status: "In Development",
    statusType: "dev",
    tags: ["Flutter", "Dart", "Supabase", "PostgreSQL", "Stripe", "BLoC"],
    modules: [
      "Grid Training",
      "Reaction Time",
      "Drill Plans",
      "Analytics",
      "History",
      "Premium",
      "Statistics",
      "Multi-platform",
    ],
    visual: {
      title: "goalie-gym · training",
      footer: ["Reaction time analytics", "Stripe subscriptions"],
    },
    link: null,
  },
  {
    id: "concentration-gym",
    kind: "grid",
    name: "Concentration Gym",
    subtitle: "Competitive Mental Training Platform",
    desc: "A full-stack web platform where athletes sharpen focus through concentration grid exercises. Players compete in real-time live sessions and tournaments, track performance across leaderboards, and follow structured weekly workout plans — all powered by SignalR multiplayer.",
    status: "Live",
    statusType: "live",
    tags: [
      "ASP.NET Core",
      "C#",
      "MySQL",
      "SignalR",
      "Razor",
      "Entity Framework",
    ],
    modules: [
      "Grid Training",
      "Tournaments",
      "Live Sessions",
      "Gamerooms",
      "Leaderboards",
      "Workout Plans",
      "Statistics",
      "Reaction Time",
    ],
    visual: {
      title: "concentration-gym · live",
      footer: ["Real-time multiplayer", "Tournament leaderboards"],
    },
    link: null,
  },
  {
    id: "eminds",
    kind: "dashboard",
    name: "Eminds Academy",
    subtitle: "Learning Management System",
    desc: "A full-stack LMS for Eminds Academy powering both admin and student portals. Covers course and batch management, live Zoom sessions, exam tracking, attendance, Stripe payments, and achievement badges — with multi-device locking and role-based access control.",
    status: "In Development",
    statusType: "dev",
    tags: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "Stripe",
      "Zoom SDK",
      "NextAuth",
    ],
    modules: [
      "Courses",
      "Live Sessions",
      "Exams",
      "Attendance",
      "Students",
      "Payments",
      "Badges",
      "Reports",
    ],
    visual: {
      title: "eminds-academy · dashboard",
      footer: ["Zoom live sessions", "Role-based access"],
    },
    link: null,
  },
  {
    id: "whatsapp-crm",
    kind: "chat",
    name: "WhatsApp CRM",
    subtitle: "Business Messaging Platform",
    desc: "A multi-tenant CRM built around the WhatsApp Business API. Teams manage conversations, assign threads to agents, track message delivery, and maintain full audit logs — all from a unified inbox with role-based access and real-time webhook integration.",
    status: "In Development",
    statusType: "dev",
    tags: [
      "Next.js",
      "TypeScript",
      "PostgreSQL",
      "Drizzle ORM",
      "NextAuth",
      "TanStack Query",
    ],
    modules: [
      "Conversations",
      "WhatsApp API",
      "Contacts",
      "Team",
      "Audit Logs",
      "Multi-account",
      "Reports",
      "Multi-tenant",
    ],
    visual: {
      title: "whatsapp-crm · inbox",
      footer: ["WhatsApp Business API", "Multi-tenant ready"],
    },
    link: null,
  },
  {
    id: "github-time-tracker",
    kind: "editor",
    name: "GitHub Time Tracker",
    subtitle: "VS Code Extension",
    desc: "A VS Code extension that tracks time spent on GitHub branches — automatically pausing after 15 minutes of inactivity and resuming when you refocus. Visualise branch work hours, save session logs, and manage time data directly from the Command Palette.",
    status: "Live",
    statusType: "live",
    tags: ["TypeScript", "VS Code API", "Node.js"],
    modules: [
      "Branch Tracking",
      "Time Tracking",
      "Auto-pause",
      "Visualisation",
      "Session Logs",
      "VS Code Extension",
      "Branch Details",
      "Work Hours",
    ],
    visual: {
      title: "github-time-tracker · vscode",
      footer: ["Auto-pause on inactivity", "VS Code Marketplace"],
    },
    link: null,
  },
  {
    id: "erp-system",
    kind: "dashboard",
    name: "ERP System",
    subtitle: "Enterprise Resource Planning",
    desc: "A feature-complete ERP for manufacturing and supply chain operations. Covers fabric purchasing, invoicing, finished goods, stock tracking, payments, and profit reporting — with role-based access, multi-database architecture, and full Excel and PDF export.",
    status: "Live",
    statusType: "live",
    tags: [
      "ASP.NET MVC",
      "C#",
      "SQL Server",
      "Entity Framework",
      "Bootstrap",
      "jQuery",
    ],
    modules: [
      "Manufacturing",
      "Purchasing",
      "Invoicing",
      "Inventory",
      "Payments",
      "Dashboard",
      "Reports",
      "Users",
    ],
    visual: {
      title: "erp-system · dashboard",
      footer: ["Multi-module ERP", "Excel & PDF export"],
    },
    link: null,
  },
  {
    id: "diagramify",
    kind: "diagram",
    name: "AI Diagramify",
    subtitle: "AI Diagram Generation · MSc Project",
    desc: "Describe any system in plain English and Gemini 1.5 Flash generates interactive diagrams instantly. Powered by specialised prompt engineering for six diagram types — flowcharts, mind maps, UML class, activity, and use case diagrams — plus a context-aware AI chat to query your generated output.",
    status: "In Development",
    statusType: "dev",
    tags: [
      "Gemini 1.5 Flash",
      "Next.js",
      "TypeScript",
      "AntV X6",
      "Vercel AI SDK",
      "Zustand",
    ],
    modules: [
      "AI Generation",
      "AI Chat",
      "Flowcharts",
      "Mind Maps",
      "Class Diagrams",
      "Prompt Engine",
      "Activity Diagrams",
      "Use Case Diagrams",
    ],
    visual: {
      title: "diagramify · ai generator",
      footer: ["Gemini 1.5 Flash", "Prompt engineering"],
    },
    link: null,
  },
];

export const STATUS = {
  dev: { color: 'var(--orange)', label: 'In development' },
  live: { color: '#22c55e', label: 'Live' },
  soon: { color: 'rgba(244,243,239,0.5)', label: 'Coming soon' },
}
